export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_ORDER = "SET_ORDER";
export const SET_ERROR = "SET_ERROR";
export const PURCHASED_BURGER_START = "PURCHASED_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FALIED";

export const FETCH_BURGER_SUCCESS = "FETCH_BURGER_SUCCESS";
export const FETCH_BURGER_FAILED = "FETCH_BURGER_FAILED";
